# Generated by Django 3.1.4 on 2021-01-01 21:58
import os

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    def generate_superuser(apps, schema_editor):
        from users.models import User
        superuser = User.objects.create_superuser(
            username=os.environ.get('DJANGO_SUPERUSER_USERNAME', 'admin'),
            email=os.environ.get('DJANGO_SUPERUSER_EMAIL', 'admin@admin.com'),
            password=os.environ.get('DJANGO_SUPERUSER_PASSWORD', 'admin'))

        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
