version: "3.3"

services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  inrad-api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/inrad
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      ./.env-sample
    environment:
      - DB_HOST=db
      - DJANGO_SETTINGS=dev
      - DEBUG=True

volumes:
  pgdata: