version: "3.3"

services:
  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      ./.env-sample
    environment:
      - DB_HOST=db
  app:
    image: alexaxms/inrad-app
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  pgdata: