# Generated by Django 3.1.4 on 2021-02-15 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical_history', '0002_auto_20201227_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient_treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='medical_history.patienttreatment'),
        ),
    ]
