# Generated by Django 3.1.4 on 2021-03-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_history', '0004_auto_20210220_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
