# Generated by Django 3.1.4 on 2021-03-20 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medical_history", "0007_auto_20210320_1736"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalappointmentimage",
            name="img_link",
        ),
        migrations.AddField(
            model_name="medicalappointmentimage",
            name="image",
            field=models.FileField(default=None, upload_to=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient_diagnostic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="medical_history.patientdiagnostic",
            ),
        ),
    ]
