# Generated by Django 3.1.4 on 2021-03-28 05:19

from django.db import migrations


def initial_disease(apps, schema_editor):
    from medical_history.models import DiseaseType, DiseaseCategory
    import csv
    import os

    workpath = os.path.dirname(os.path.abspath(__file__))
    c = open(os.path.join(workpath, "../../codes.csv"))
    csv_reader = csv.reader(c, delimiter=",")
    category = DiseaseCategory.objects.first()
    for row in csv_reader:
        try:
            if category.code != row[0]:
                category = DiseaseCategory.objects.get(code=row[0])
            category.diseases.create(name=row[3], code=row[2], description=row[5])
        except:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("medical_history", "0010_auto_20210328_0501"),
    ]

    operations = [
        migrations.RunPython(initial_disease),
    ]
