# Generated by Django 3.1.4 on 2021-04-03 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medical_history", "0012_auto_20210328_1634"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicalappointmentimage",
            old_name="medical_appointment_summary",
            new_name="appointment",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="blood_type",
        ),
        migrations.CreateModel(
            name="MedicalAppointmentSymptom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="symptoms",
                        to="medical_history.appointment",
                    ),
                ),
                (
                    "symptom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="appointments",
                        to="medical_history.appointment",
                    ),
                ),
            ],
        ),
    ]
