# Generated by Django 3.1.4 on 2021-04-04 23:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('medical_history', '0014_auto_20210403_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 4, 23, 13, 2, 691300, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='health_facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='derived_patients', to='medical_history.healthfacility'),
        ),
    ]
