# Generated by Django 3.1.4 on 2021-04-11 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medical_history", "0015_auto_20210404_2313"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalForecast",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="patient",
            name="age",
        ),
        migrations.AddField(
            model_name="patient",
            name="birth_date",
            field=models.DateField(default="2012-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_forecast",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="related_patients",
                to="medical_history.medicalforecast",
            ),
        ),
    ]
