# Generated by Django 3.1.4 on 2021-04-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_history', '0016_auto_20210411_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasetype',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patientdiagnostic',
            name='description',
            field=models.TextField(),
        ),
    ]
